### PR TITLE
Added README and Japanese translation.

### PR DESCRIPTION
**Pull request by reindex-ot**
The Japanese translation of the application is partially in English because some of the notation is garbled.

### CODE REVIEW

**Comment by reindex-ot** [comment]
README update.

**Comment by r57zone** [comment]
Thanks

**Comment by r57zone** [comment]
I updated the release archive, could you check if everything is fine?
https://github.com/r57zone/Firewall-Easy/releases/

**Comment by reindex-ot** [comment]
okay
I will check back later.

**Comment by r57zone** [comment]
Hi! I've updated the translations — the file is now in UTF-8. If you could test your language, that would be great. Thank you in advance!
https://github.com/r57zone/FirewallEasy/releases/

**Pull request merged**
