### PR TITLE
French Translation By Largo

### PR DESCRIPTION
**Pull request by logounet**
Hello,

Here is the French Translation for "Firewall.Easy.0.7" if you agree

Best regards

Largo

### CODE REVIEW

**Comment by r57zone** [comment]
Thanks

**Comment by r57zone** [comment]
https://github.com/r57zone/Firewall-Easy/releases 
I have updated the release, could you check if everything is ok with French?

**Comment by logounet** [comment]
Hello,

My translation should be encoded in AINSI, and not in UTF-8 if it's possible, because in French there are a lot of accents on certain words or verbs. In UTF-8 this does not display correctly, Example: Règles In AINSI becomes RÃ~gles in UTF-8, in French.
French is a complex language, an accent on a word changes its meaning or does not exist.
See attached images.

Best regards




 
From: Кладовая
Date: 2022-10-17 12:15
To: r57zone/Firewall-Easy
CC: logounet; Author
Subject: Re: [r57zone/Firewall-Easy] French Translation By Largo (PR #5)
https://github.com/r57zone/Firewall-Easy/releases
I have updated the release, could you check if everything is ok with French?

**Comment by r57zone** [comment]
Could you save the file in ANSI in notepad? Check and submit? Thanks

**Comment by logounet** [comment]
Hello,

Here is the File converted to AINSI.
See attached file.



 
From: Кладовая
Date: 2022-10-17 13:54
To: r57zone/Firewall-Easy
CC: logounet; Author
Subject: Re: [r57zone/Firewall-Easy] French Translation By Largo (PR #5)
Could you save the file in ANSI in notepad? Check and submit? Thanks

**Comment by r57zone** [comment]
Could you upload to github? by mail github does not include the file

**Comment by logounet** [comment]
Hello,

No problems detected.

See you later.



 
From: Кладовая
Date: 25-05-2025 12:50
To: r57zone/FirewallEasy
CC: logounet; Author
Subject: Re: [r57zone/FirewallEasy] French Translation By Largo (PR #5)
r57zone left a comment (r57zone/FirewallEasy#5)
Hi! I've updated the translations — the file is now in UTF-8. If you could test your language, that would be great. Thank you in advance!
https://github.com/r57zone/FirewallEasy/releases/

**Comment by r57zone** [comment]
Thanks for checking!

**Pull request merged**
